apiVersion: apps/v1
kind: Deployment
metadata:
  name: boonya-game-lab
spec:
  replicas: 3 # 希望运行的Pod副本数
  selector:
    matchLabels:
      app: boonya-game-lab
  template:
    metadata:
      labels:
        app: boonya-game-lab
    spec:
      containers:
        - name: boonya-game-lab
          image: docker.io/boonyadocker/boonya-game-lab:latest # 替换为你的镜像地址
          ports:
            - containerPort: 8080 # 容器端口
          env: # 可选：设置环境变量
            - name: JAVA_OPTS
              value: "-Xmx512m"
          # 可以添加资源限制和健康检查
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health # 假设使用Spring Actuator的健康检查端点
              port: 8080
            initialDelaySeconds: 90 # 容器启动后多久开始探测
            periodSeconds: 10 # 执行探测的频率
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: boonya-game-lab-service
spec:
  selector:
    app: boonya-game-lab
  ports:
    - protocol: TCP
      port: 80 # Service端口
      targetPort: 8080 # 容器端口
  # type: ClusterIP # 默认类型，集群内访问
  type: LoadBalancer # 如果希望从集群外部访问，可以使用LoadBalancer（云提供商通常支持）或NodePort
