spring:
  application:
     name: boonya-game-jmh
  # 数据源
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/master_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: master_password
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5

    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://slave1:3306/slave_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: slave_password
      hikari:
        maximum-pool-size: 15
        minimum-idle: 3

    slave2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://slave2:3306/slave_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: slave_password
      hikari:
        maximum-pool-size: 15
        minimum-idle: 3
