spring:
  application:
    name: boonya-game-ai
  # AI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-your-openai-key-here} # api_key
      base-url: https://api.openai.com # Azure OpenAI
      chat:
        options:
          model: gpt-3.5-turbo # use gpt-4
          temperature: 0.7
  # PG vector database
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    # connection pool
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  # Jpa
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
