# coze-tool-config.yaml
name: "boonya_rag"
description: "Document-based question answering using RAG"
parameters:
  type: "object"
  properties:
    session_id:
      type: "string"
      description: "Conversation session ID"
    question:
      type: "string"
      description: "The question to ask"
    prompt_type:
      type: "string"
      enum: ["default", "detailed", "concise"]
      description: "Type of prompt to use"
  required:
    - "question"
endpoint:
  url: "http://localhost:8080/api/rag/ask"
  method: "POST"