apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boonya-game-lab-ingress
spec:
  rules:
    - host: www.boonya.tech  # 将域名映射到你的服务
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boonya-game-lab-service # 这里指向一个普通的 ClusterIP Service
                port:
                  number: 80