apiVersion: v1
kind: Service
metadata:
  name: boonya-game-lab-lb-service
spec:
  type: LoadBalancer   # 关键：设置类型为 LoadBalancer
  selector:
    app: boonya-game-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080